---
title: "cw4"
author: "grzegorz"
date: "2024-10-29"
output: html_document
---

#instalacja pakietu Biocmanger

```{r}
install.packages("BiocManager")
```

```{r}
BiocManager::install("GenomicFeatures")
BiocManager::install("AnnotationDbi")
BiocManager::install("ShortRead")
BiocManager::install("Biostrings")
```

```{r}
library('GenomicFeatures')
```

```{r}
installed.packages("BiocManager")
```

```{r}
BiocManager::install("GenomicFeatures")
```

```{r}
library("AnnotationDbi")
```

```{r}
library("ShortRead")
```

```{r}
library("Biostrings")
```

```{r}
BiocManager::install("ShortRead")
```

```{r}
install.packages("MatrixGenerics")
```

```{r}
install.packages("BiocManager")
```

```{r}
install.packages("markdown")
```

```{r}
library(markdown)
```

```{r}
install.packages("markdown")
```
```{r}
dnasekw<-readDNAStringSet("C:/Users/s207318/Desktop/analizacw/examples.fasta")

```
```{r}
dnasekw[1:5]
```
```{r}
gc_content <- letterFrequency(dnasekw, letters = c("G", "C"), as.prob = TRUE)
```
```{r}
rev_comp_seqs<-reverseComplement(dnasekw)
```
```{r}
rev_comp_seqs[1:5]
```
```{r}
gc_content
```




